### PR TITLE
Enhance Asset & Case Information API with Validation, Filtering & Ownership Updates

### LINKED ISSUE #33: wrong time zone for utc and local time
# need to repair soon  🕐🕐
* Time format is wrong 
* UTC time not converted first into local timezone 🌎
* api req timezone 

# 🚀🚀🚀🚀

### PR DESCRIPTION
**Pull request by Miku21750**
# 🚀 Enhance Asset & Case Information API with Validation, Filtering & Ownership Updates

## 🛠 Overview
This PR introduces several improvements to the **Asset & Case Information API**, refining data validation, filtering logic, and ownership updates. It also enhances **UI components** such as `BtnModalAsset` and `TableCompany`, ensuring better asset selection and contact assignment.

### ✅ Fixes & Enhancements:
- **Asset Information API:**
  - Added `site_account`, `contact_information`, and `product_information` to asset retrieval.
  - Improved filtering & sorting by `ProductName`.
  - Corrected filtering for unowned assets (`ContactID: 0` → `null`).
  - Enhanced logging for `WHERE` conditions.

- **Case Information API:**
  - Fixed `CreatedOn` formatting for proper Indonesian locale (`id-ID`).
  - Improved case data mapping.

- **Asset Selection (`BtnModalAsset`):**
  - Optimized asset fetching (owned & unowned assets).
  - Updated `ContactID` & `SiteAccountID` together on assignment.
  - Improved search & pagination handling.

- **Company & Contact Selection (`TableCompany`):**
  - Improved state management for `selectedContactForCase`.
  - Clicking a contact updates `selectedContact` & `selectedContactForCase`.
  - Auto-selects related contact when an asset is chosen.

### 🐛 Bug Fix:
Fixes issue #33 :  
✅ **Corrected UTC & local time zone handling** for case information timestamps.

## 🔍 How to Test:
1. Fetch the latest branch & install dependencies.
2. Test asset filtering (`GET /api/asset-information/kepemilikan`).
3. Verify asset ownership updates (`PATCH /api/asset-information/kepemilikan/[AssetID]`).
4. Ensure proper contact assignment & asset selection behavior in UI.
5. Validate `CreatedOn` timestamps in the `id-ID` locale.

## 📌 Why This Matters:
- Ensures accurate data retrieval & filtering.
- Improves UI responsiveness and user experience.
- Fixes **incorrect time zone formatting** in case information.

🔗 **Ready for review!** 🚀 Let me know if any adjustments are needed. 🙌

### CODE REVIEW

File: next-api/src/app/api/asset-information/kepemilikan/[AssetID]/route.js [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+        });
+
+        return NextResponse.json({
+            success: true,
+            message: "Asset contact successfully updated!",
+            data: updatedAsset
+        }, { status: 200 });
+
+    } catch (error) {
+        console.error("🔥 ERROR in PATCH API (Update Asset Contact):", error);
```
Comment (Mackovlak) [inline next-api/src/app/api/asset-information/kepemilikan/[AssetID]/route.js:54]: #FIREE 🥇

File: next-api/src/app/api/asset-information/kepemilikan/route.js
Comment (Mackovlak) [inline next-api/src/app/api/asset-information/kepemilikan/route.js:1]: ## Redundant

File: test-vite/src/components/info-case.jsx [hunk 2]
```diff
@@ -0,0 +1,79 @@
+"use client"
```
Comment (Mackovlak) [inline test-vite/src/components/info-case.jsx:1]: ## what is this

**Review by Mackovlak — APPROVED** [review]
#38 Has Been Approve By @Mackovlak 
* Merging new feature to the branch
